### PR TITLE
Literally just forgot a JS resource

### PR DESCRIPTION
**Pull request by mike-bailey**
As the title says... It wasn't in the same block in index.coffee so it escaped me.
Also my dev workload was running on HTTP but I didn't notice until it merged and I visited https://hiddentao.github.io/ois-incidents-map/. I moved my workload to HTTPS before pushing this.

You can verify it works at https://dev.michaelbailey.co until you pull this.

### CODE REVIEW

**Comment by hiddentao** [comment]
Thanks, was just about to fix this myself.

**Comment by mike-bailey** [comment]
Worth noting you're still missing your "green lock" from Google Chrome, mainly because of the Map loading CDN.

Changing it to something like:
https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/3/1/1.png from http://a.basemaps.cartocdn.com/light_all/3/1/3.png

I could do this myself but I already gave you two PRs in rapid succession so it's your call whether you want a third on the project.

Didn't do this in the last PR because I just found the CDN endpoint...

**Comment by hiddentao** [comment]
Done. Thanks for the tips. I haven't worked on this for a while. I'd probably use something like React if I did it again. More importantly, I wish there was a better data source to draw data from.

**Comment by mike-bailey** [comment]
Fair. data.gov tries to maintain SOME but then you're 
1. at their mercy
2. dealing with a ton of localities and aggregating different formats

I just visited [Google Trends](https://www.google.com/trends/hottrends) and it dawned on me how a project like this could still be just as if not more beneficial today.

**Pull request merged**
